export enum FlightStatus {
  Scheduled = 'scheduled',
  OnTime = 'onTime',
  Delayed = 'delayed',
  Cancelled = 'cancelled',
  Departed = 'departed',
  InAir = 'inAir',
  Landed = 'landed',
  Arrived = 'arrived',
  Diverted = 'diverted',
  GateChanged = 'gateChanged',
  Boarding = 'boarding',
  FinalCall = 'finalCall',
  GateClosed = 'gateClosed',
  CheckInOpen = 'checkInOpen',
  CheckInClosed = 'checkInClosed',
  Unknown = 'unknown',
}
